### ISSUE TITLE
1주차 학습: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가.

### ISSUE THREAD

**Issue by wonju-dev** [KMUCS-MoGakKo/Java_Study#1]
# 목표
- 자바 소스 파일(.java)을 JVM으로 실행하는 과정 이해하기.

# 학습할 것
- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

# 마감 일시
- 2022년 09월 22 오후 6시

**Comment by devbelly** [comment]
1주차 학습내용입니다.
https://devbelly.github.io/java-kotlin/JAVA-JVM-architecture/

**Comment by mjjunng** [comment]
1주차 학습 내용입니다.
[https://github.com/mjjunng/TIL/blob/main/Java/JVM.md](https://github.com/mjjunng/TIL/blob/main/Java/JVM.md)

**Comment by wonju-dev** [comment]
1주차 학습 내용입니다.
[학습 내용](https://velog.io/@314_dev/JVM%EC%9D%80-%EB%AC%B4%EC%97%87%EC%9D%B4%EB%A9%B0-%EC%9E%90%EB%B0%94-%EC%BD%94%EB%93%9C%EB%8A%94-%EC%96%B4%EB%96%BB%EA%B2%8C-%EC%8B%A4%ED%96%89%ED%95%98%EB%8A%94-%EA%B2%83%EC%9D%B8%EA%B0%80
)
1. 공부하다 [야크 털 깎는 상황](https://www.lesstif.com/software-engineering/yak-shaving-29590364.html)이 발생해서 분량이 좀 늘어났습니다ㅜㅜ
2. 발표 내용을 전부 적어 놓으면, 똑같은 내용을 또 들어서 지루할 것 같다는 생각이 들었습니다.
    - 그러다보니 내용이 좀 매끄럽게 이어지지 않거나, 부족한 부분이 있습니다. 잘 이해가 되지 않으시면 질문해 주세요!!

**Comment by identity230c** [comment]
1주차 학습내용입니다. 

https://velog.io/@asdf2end/JVM

**Comment by kjsoo-1010** [comment]
1주차 학습 내용입니다.
늦어서 죄송합니다 ㅠㅠ
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/1%EC%A3%BC%EC%B0%A8%20_%20JVM.pdf
