### ISSUE TITLE
3주차 학습: 클래스

### ISSUE THREAD

**Issue by kjsoo-1010** [KMUCS-MoGakKo/Java_Study#10]
# 목표
- 자바의 Class에 대해 학습하세요.

# 학습할 것
- 클래스 정의하는 방법
- 객체 만드는 방법 (new 키워드 이해하기)
- 메소드 정의하는 방법
- 생성자 정의하는 방법
- this 키워드 이해하기

# 마감일시
- 2022-10-06 18:00

**Comment by devbelly** [comment]
3주차 학습내용입니다.
https://devbelly.github.io/java-kotlin/JAVA-%EC%9E%90%EB%B0%94-%ED%81%B4%EB%9E%98%EC%8A%A4/

**Comment by identity230c** [comment]
3주차 학습내용입니다
https://velog.io/@asdf2end/KMUCS-MOGAKKO-JAVA-Class

**Comment by kjsoo-1010** [comment]
3주차 학습 내용입니다
개념을 확실히 알고 싶어서 여기저기 삽질을 많이 했더니 다른 분들에 비해 너무 부실해보이네요.. 이상 비겁한 변명이었습니다... 내일 발표 전까지 발표 자료 좀 더 보완해보겠습니다..! 
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/3%EC%A3%BC%EC%B0%A8%20%EA%B3%BC%EC%A0%9C_%20%ED%81%B4%EB%9E%98%EC%8A%A4.pdf

**Comment by wonju-dev** [comment]
[3주차 정리 내용](https://velog.io/@314_dev/%ED%81%B4%EB%9E%98%EC%8A%A4)

이번주 내내 몸살감기 + 예비군때문에 내용을 다 다루지 못했습니다 ㅠㅠ 오늘 9시까지는 정리해보도록 하겠습니다!!!

[자바스크립트는 왜 프로토타입을 선택했을까](https://medium.com/@limsungmook/%EC%9E%90%EB%B0%94%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%8A%94-%EC%99%9C-%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85%EC%9D%84-%EC%84%A0%ED%83%9D%ED%96%88%EC%9D%84%EA%B9%8C-997f985adb42)
