### ISSUE TITLE
this는 언제 생성되는걸까요

### ISSUE THREAD

**Issue by wonju-dev** [KMUCS-MoGakKo/Java_Study#11]
여러 아티클에서 `this`를 인스턴스를 참조하는 **변수**라고 설명하는데

우리가 일반적으로 생각하는 지역 변수와 동일한 특징을 가지는 걸까요?

`this`가 일반적인 지역 변수라면
1. 메모리 어느 영역에 저장되는 걸까요
2. 메소드 호출시에 누가 this라는 변수를 만들어주는 걸까요

**Comment by kjsoo-1010** [comment]
아이고... 좀 더 찾아보고 답변 달아보려고 했는데 스터디 때 이야기 나온 것 외에는 자료를 더 찾지 못했습니다 ㅠㅠ 부족하지만 스터디 때 나온 답변 위주로 정리해서 내일 중으로 올리겠습니다!

**Comment by identity230c** [comment]
https://homoefficio.github.io/2019/01/31/Back-to-the-Essence-Java-%EC%BB%B4%ED%8C%8C%EC%9D%BC%EC%97%90%EC%84%9C-%EC%8B%A4%ED%96%89%EA%B9%8C%EC%A7%80-2/

찾았습니다
메서드가 호출될때 stack에 0번에 제일 먼저 저장된다고 하네요
