### ISSUE TITLE
4주차 학습: 상속

### ISSUE THREAD

**Issue by identity230c** [KMUCS-MoGakKo/Java_Study#12]
# 목표
- 자바의 상속을 공부하시오
# 학습할 것 
- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치
- 추상 클래스
- final 키워드
- Object 클래스

**Comment by identity230c** [comment]
4주차 학습내용입니다 
https://velog.io/@asdf2end/KMUCS-MOGAKKO-JAVA-%EC%83%81%EC%86%8D

**Comment by devbelly** [comment]
4주차 학습내용입니다.
https://devbelly.github.io/java-kotlin/JAVA-%EC%83%81%EC%86%8D/
- 시간이 오래 걸려서 final, Object 내용은 시험기간 이후 추가하도록 하겠습니다.

**Comment by kjsoo-1010** [comment]
~~_죄송합니다... 마무리 정리가 조금 덜 되어서, 질문만 미리 올리고 8시 전까지 제출하도록 하겠습니다ㅠㅠ_~~
4주차 내용입니다 뒤로 갈수록 힘이 빠지는 게 눈에 보이네요😭
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/4%EC%A3%BC%EC%B0%A8_%20%EC%83%81%EC%86%8D.pdf

**Comment by wonju-dev** [comment]
4주차 내용입니다.

https://velog.io/@314_dev/%EC%83%81%EC%86%8D

**Comment by mjjunng** [comment]
4주차 학습내용입니다. 
준비 시간이 부족해서 깊이있게 공부를 못했네요ㅠ 개념 정리하는 느낌으로 작성했습니다. 
[https://blog.naver.com/mjjunghp/222899452856](https://blog.naver.com/mjjunghp/222899452856)
