### ISSUE TITLE
[4주차] 왜 생성자는 상속되지 않고 호출되나요..?

### ISSUE THREAD

**Issue by kjsoo-1010** [KMUCS-MoGakKo/Java_Study#13]
_'부모 클래스의 생성자는 상속되지 않고, 자식 클래스로 인스턴스를 생성할 때 자동적으로 부모의 기본 생성자가 호출된다'_

부분을 보다가 왜 생성자는 상속되지 않고 호출되는 건지 궁금해져서 찾아보는데, 잘 이해가 되지 않아 질문 남깁니다!

생성자가 부모 클래스에만 존재해야 하는 이유가 있을까요..?

**Comment by identity230c** [comment]
상속자가 메서드가 아닌 인스턴스 초기화를 위한 객체 초기화를 위한 코드블럭이기 때문입니다.

따라서 class의 member에 해당하지 않아 상속의 대상도 아니며, 오버라이딩이 되지 않습니다
[참고자료 : 생성자(Constructor)도 메소드인가?](https://javacan.tistory.com/entry/37)
