### ISSUE TITLE
5주차 학습: 패키지

### ISSUE THREAD

**Issue by mjjunng** [KMUCS-MoGakKo/Java_Study#14]
# **목표**

자바의 패키지에 대해 학습하세요.

# **학습할 것**

- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- classpath 옵션
- 접근지시자

**Comment by wonju-dev** [comment]
5주차 학습 내용입니다

https://velog.io/@314_dev/%ED%8C%A8%ED%82%A4%EC%A7%80

계속해서 내용 추가하겠습니닷

**Comment by devbelly** [comment]
5주차 학습내용입니다.

https://devbelly.github.io/java-kotlin/JAVA-%ED%8C%A8%ED%82%A4%EC%A7%80/

**Comment by identity230c** [comment]
[5주차 학습내용](https://velog.io/@asdf2end/KMUCS-MOGAKKO-JAVA-%ED%8C%A8%ED%82%A4%EC%A7%80)

뜬금없이 주제 package와 무관한 java module에 관한 내용이 추가되어 있습니다...

**Comment by mjjunng** [comment]
5주차 학습 내용입니다.
[https://blog.naver.com/mjjunghp/222918588301](https://blog.naver.com/mjjunghp/222918588301)

**Comment by kjsoo-1010** [comment]
5주차 학습 내용입니다!
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/5%EC%A3%BC%EC%B0%A8_%20%ED%8C%A8%ED%82%A4%EC%A7%80.pdf

https://docs.google.com/document/d/11ttrYX2FR352gxaoysxwHEyAMTo95rjrTQvc7SDxsRQ/edit?usp=sharing
