### ISSUE TITLE
6주차 학습: 인터페이스

### ISSUE THREAD

**Issue by wonju-dev** [KMUCS-MoGakKo/Java_Study#15]
# 목표
- 자바의 인터페이스에 대해 학습하세요.

# 학습할 것
- 인터페이스 정의하는 방법
- 인터페이스 구현하는 방법
- 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
- 인터페이스 상속
- 인터페이스의 기본 메소드 (Default Method), 자바 8
- 인터페이스의 static 메소드, 자바 8
- 인터페이스의 private 메소드, 자바 9

# 마감 일시
- 2022년 11월 10일 오후 6시

**Comment by wonju-dev** [comment]
https://velog.io/@314_dev/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4

인터페이스 관련해서 헷갈렸던 점 위주로 정리했습니닷

**Comment by identity230c** [comment]
[6주차 학습내용입니다](https://velog.io/@asdf2end/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4)

**Comment by devbelly** [comment]
https://devbelly.github.io/java-kotlin/JAVA-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4/
6주차 학습내용입니다.

**Comment by mjjunng** [comment]
6주차 학습내용입니다. 
[https://blog.naver.com/mjjunghp/222925623811](https://blog.naver.com/mjjunghp/222925623811)

**Comment by kjsoo-1010** [comment]
지각 죄송합니다😭 6주차 학습내용입니다!
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/6%EC%A3%BC%EC%B0%A8_%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4.pdf
