### ISSUE TITLE
7주차 학습: 예외 처리

### ISSUE THREAD

**Issue by devbelly** [KMUCS-MoGakKo/Java_Study#16]
# 목표
- 자바의 예외 처리에 대해 학습하세요

# 학습할 것
- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법

# 마감 일시
- 2022년 11월 17일 오후 6시

**Comment by devbelly** [comment]
7주차 학습내용입니다.
https://devbelly.github.io/java-kotlin/JAVA-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC/

**Comment by wonju-dev** [comment]
7주차 내용입니다
https://velog.io/@314_dev/%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC

계속 업데이트 하겠습니다 ㅠㅠ

**Comment by mjjunng** [comment]
7주차 학습내용입니다.
[https://blog.naver.com/mjjunghp/222931161427](https://blog.naver.com/mjjunghp/222931161427)
이어서 내용 추가하겠습니다.

**Comment by identity230c** [comment]
[7주차 학습내용입니다.](https://velog.io/@asdf2end/KMUCS-MOGAKKO-JAVA-%EC%98%88%EC%99%B8)

**Comment by kjsoo-1010** [comment]
7주차 학습내용입니다!
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/7%EC%A3%BC%EC%B0%A8_%EC%98%88%EC%99%B8%20%EC%B2%98%EB%A6%AC.pdf
