### ISSUE TITLE
8주차 학습: 멀티쓰레드 프로그래밍

### ISSUE THREAD

**Issue by identity230c** [KMUCS-MoGakKo/Java_Study#17]
# 목표
- 자바의 멀티쓰레드 프로그래밍에 대해 학습하세요.

# 학습할 것 (필수)
- Thread 클래스와 Runnable 인터페이스
- 쓰레드의 상태
- 쓰레드의 우선순위
- Main 쓰레드
- 동기화
- 데드락

# 마감일시
- 2022년 11월 23일 오후 6시

**Comment by identity230c** [comment]
[8주차 학습내용입니다. ](https://velog.io/@asdf2end/KMUCS-mogakko-java-%EB%A9%80%ED%8B%B0%EC%93%B0%EB%A0%88%EB%93%9C%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D)

**Comment by devbelly** [comment]
8주차 학습내용입니다.
https://devbelly.github.io/java-kotlin/JAVA-%EB%A9%80%ED%8B%B0%EC%93%B0%EB%A0%88%EB%93%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/

**Comment by wonju-dev** [comment]
8주차 내용입니다

https://velog.io/@314_dev/%EB%A9%80%ED%8B%B0%EC%93%B0%EB%A0%88%EB%93%9C-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D

**Comment by mjjunng** [comment]
8주차 학습내용입니다. 이어서 내용 추가하겠습니다.
[https://blog.naver.com/mjjunghp/222937270727](https://blog.naver.com/mjjunghp/222937270727)

**Comment by kjsoo-1010** [comment]
죄송합니다 정신이 없어 늦었습니다 ㅠㅠ 천천히(..) 내용 추가하겠습니다

https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/8%EC%A3%BC%EC%B0%A8_%EB%A9%80%ED%8B%B0%EC%93%B0%EB%A0%88%EB%93%9C%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D.pdf
