### ISSUE TITLE
[1주차] classloader에서 resolution단계의 역할

### ISSUE THREAD

**Issue by devbelly** [KMUCS-MoGakKo/Java_Study#3]
Classloader의 linking-resolution에서 "symbolic Reference 값을 JVM의 메모리 구성 요소인 Method Area의 런타임 환경 풀을 통하여 Direct Reference라는 메모리 주소 값으로 변경" 로 설명이 되어있습니다. 

자바에서는 실행 도중 symbolic reference를 만나게 되면 runtime constant pool을 활용해서 direct reference을 얻어 접는 하는 것으로 이해했는데 resolution에서는 이 때 활용하기 위한 direct reference를 runtime constant pool에 저장을 하는 건가요?

**Comment by kjsoo-1010** [comment]
https://blog.hexabrain.net/397

**Comment by wonju-dev** [comment]
# 바이트 코드의 구조
- 영역의 이름은 제가 임의로 지었습니다. 
## 1. Class Meta data 
- `어떤 버전의 자바 컴파일러로 컴파일 했는가` 등의 메타 데이터를 저장하는 공간 공간
- Classloader의 linking phase의 Verification 작업에서 바이트 코드의 유효성을 검증
## 2. Constant Pool
- `symbolic link`와 실제 데이터(주소값, 상수값, 클래스 이름 등)의 mapping 정보를 저장하는 공간
## 3. Code Area
- JVM virtual machine assembly language에 따라 컴파일된 클래스의 메소드 코드가 위치하는 곳
- virtual machine assembly language에 사용되는 데이터(메소드 주소, 상수값, 변수 값 등등 모든 데이터)는 symbolic link상태로 있음
- JVM의 종류에 따라 다음 처럼 작동할 수 있음
    1. Classloader의 linking phase의 resolution 작업에서 symbolic link -> direct reference로 변경
    2. 컴파일 타임에 모든 symbolic link -> direct reference로 변경

# 참고 
https://blog.hexabrain.net/397
