### ISSUE TITLE
[1주차] JIT compiler에서 threshold의 기준

### ISSUE THREAD

**Issue by devbelly** [KMUCS-MoGakKo/Java_Study#4]
threshold의 기준이 

1. method entry counter (JVM 내에 있는 메서드가 호출된 횟수)
2. back-edge loop counter (메서드가 루프를 빠져나오기까지 돈 횟수)

라고 되어있는데 정확히 무슨 차이인지 모르겠습니다. 저도 공부하면서 본 내용인데, 메서드가 호출된 횟수나 루프를 빠져나오기까지 돈 횟수는 결국 동일한 개념 아닌가요? 루프 내에서 메서드가 호출되어야 메서드가 루프에서 빠져나오니...

**Comment by identity230c** [comment]
개인적인 생각인데 후자의 경우에는 많이 호출되지는 않지만 한번 호출되면 그 안에서 loop를 많이 도는 메서드를 의미한다고 생각합니다.

기계어로 번역했을때 계속 똑같은 명령어들을 번역->실행을 반복하는데 이런 경우에는 캐싱하는게 유리하지 않을까요. 

호출횟수를 기준으로 했을 때는 이런 메서드에 대해 효율을 담보하기 어렵다고 생각해서 구분 한 거 같습니다.

def f():
    print("hello")

def g():
    for i in range(100_0000):
         print("hello")

def main()
{
     for i in range(100_0000)
{          
f()
}
     g()
}
이 경우 두 메서드 모두 print문을 100만번 시행하는 것 똑같지만 호출횟수를 기준으로 하면 g()는 캐싱대상이 아니게 되는거니까요

**Comment by devbelly** [comment]
아하 맞는 말씀이신 것 같습니다! 감사합니다

**Comment by wonju-dev** [comment]
# JIT 컴파일러는 여러 부품(?)들로 구성되어 있다고 추측됨.
그 중 우리는 2개의 부분에 대해 집중적으로 살펴봄
1. 컴파일 담당 부분
    profiling을 통해, 해당 코드블록은 얼마의 컴파일 중요도를 가지는지 분석함
        0: 그냥 인터프리터로 해석해도 문제 X
        1~3: C1 컴파일러로 해석할만한 중요도
        4: C2 컴파일러로 해석할만한 중요도

2. `컴파일을 해야 하는가?` 판단하는 부분 

컴파일은 단순히 기계어로 번역하는 작업을 넘어, **'효율적인 코드'를 생성해야 함**
JIT 컴파일러 작동을 살펴보기 전에 static compiler, dynamic compiler를 비교했음

1. static compiler
- 컴파일을 실행 전에 미리 수행 -> 성능 이점
- 실행을 안 해보고 컴파일 때림 -> 컴파일 정확도가 떨어질 수 있음
2. dynamic compiler
- 실행 중에 컴파일 -> 성능이 약간 떨어짐
- 실행 중에 모은 메타 데이터를 기반으로 컴파일 -> 높은 컴파일 정확도 & 잘못된 컴파일을 수정할 수 있음 (recompilation)

`컴파일을 해야 하는가?` 판단을 위해 프로그램 실행에 대한 메타 데이터가 필요함
그 데이터를 모으는 작업 = `profiling`

`컴파일을 해야 하는가?` 판단은 부분은 두 가지 지표에 따름 (2개의 카운터)
1. method entry counter: 메소드(코드 블록)가 몇 번 호출되었는가 카운팅
3. back-edge loop counter: 코드블록 index가 몇 번 역행했는가
    코드블록 index가 역행하는 상황은 대표적으로 loop이 해당 / 특정 비즈니스 로직이 반복되어 호출됨 -> 컴파일 대상

# 참고
http://cr.openjdk.java.net/~vlivanov/talks/2015_JIT_Overview.pdf
