### ISSUE TITLE
2주차 학습: 자바 데이터 타입, 변수 그리고 배열, 연산자, 제어문

### ISSUE THREAD

**Issue by devbelly** [KMUCS-MoGakKo/Java_Study#5]
# 목표
- 자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법을 익힙니다.
- 자바가 제공하는 다양한 연산자를 학습하세요.
- 자바가 제공하는 제어문을 학습하세요.

# 학습할 것
- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var
- 산술 연산자
- 비트 연산자
- 관계 연산자
- 논리 연산자
- instanceof
- assignment(=) operator
- 화살표(->) 연산자
- 3항 연산자
- 연산자 우선 순위
- 선택문
- 반복문

# 마감 일시
- 2022-09-29 18:00

**Comment by devbelly** [comment]
2주차 학습 내용입니다.
https://devbelly.github.io/java-kotlin/JAVA-%EC%9E%90%EB%B0%94-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85-%EB%B0%8F-%EB%B3%80%EC%88%98/

**Comment by kjsoo-1010** [comment]
2주차 학습내용입니다!
https://github.com/kjsoo-1010/JAVA_STUDY/blob/main/2%EC%A3%BC%EC%B0%A8%20_%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%83%80%EC%9E%85_%EB%B3%80%EC%88%98_%EB%B0%B0%EC%97%B4_%EC%97%B0%EC%82%B0%EC%9E%90_%EC%A0%9C%EC%96%B4%EB%AC%B8.pdf

**Comment by wonju-dev** [comment]
3개의 포스트로 나눠서 작성했습니다

[자바 데이터 타입, 변수 그리고 배열](https://velog.io/@314_dev/%EC%9E%90%EB%B0%94-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85-%EB%B3%80%EC%88%98-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%B0%B0%EC%97%B4)
[연산자](https://velog.io/@314_dev/%EC%97%B0%EC%82%B0%EC%9E%90)
[제어문](https://velog.io/@314_dev/%EC%A0%9C%EC%96%B4%EB%AC%B8)

알고 있던 내용은 빼고 작성하려다 보니 내용이 좀 부실한것 같네요...ㅠ

**Comment by identity230c** [comment]
2주차 학습내용입니다

[변수, 연산자, 제어문](https://velog.io/@asdf2end/KMUCS-MoGakKo-Java-%EB%B3%80%EC%88%98-%EC%97%B0%EC%82%B0%EC%9E%90-%EC%A0%9C%EC%96%B4%EB%AC%B8)

**Comment by mjjunng** [comment]
2주차 학습 내용입니다.
[자바 데이터 타입, 변수, 배열](https://blog.naver.com/mjjunghp/222886083155)
[연산자](https://blog.naver.com/mjjunghp/222885143324)
[제어문](https://blog.naver.com/mjjunghp/222886091171)
