### ISSUE TITLE
[2주차] 전역 변수는 초기화를 하지 않아도 되고 지역 변수는 초기화를 해야하는 이유가 뭘까요?

### ISSUE THREAD

**Issue by kjsoo-1010** [KMUCS-MoGakKo/Java_Study#6]
찾아보다가 정확한 이유는 오라클 문서에서도 나오지 않는다고 하더라구요..ㅠ 그래서 사람들이 각자 자기가 생각하는 이유를 말해보던데 스터디에서 이 부분에 대해 다른 분들 의견도 들어보고 싶어 가져왔습니다!

**Comment by wonju-dev** [comment]
https://stackoverflow.com/questions/1560685/why-must-local-variables-including-primitives-always-be-initialized-in-java

1. 명시적으로 초기화되지 않은 변수를 다루는 것은 예상치 못한 결과를 야기한다.
2. 따라서, 초기화되지 않은 변수에 접근하는 행위를 막고자 컴파일 타임에 검출하자
3. local variable은 특정 메소드에서 실행된다는 사실이 정해져 있는 반면, instance, class variable은 언제, 어디서 접근할지 컴파일러가 알 수 없다.
5. 어쩔 수 없이(?) instance, class variable에 대해선 default value를 허용해 주자

라고 짧은 영어 실력으로 해석해 봤습니다

**Comment by devbelly** [comment]
효율성의 차이라고 생각됩니다.
java에서 global variable이란 Instance variable + class varaible입니다. 

class variable은 컴파일 타임에 초기화가 되는데 이는 런타임에 수행되는 연산이 아니므로 실행시간 문제를 일으키지 않습니다.
그에 반해 local variable은 런타임에 스택에 로드되며 사용되는데 생성할때마다 0으로 초기화 하는 작업은 런타임에 부담이 갈 것이라고 예상됩니다.

그 중간쯤 있는 Instance variable은 객체가 생성되며 객체와 함께 heap에 할당되는데... 이 부분은 왜 0으로 초기화가 되는지 잘 모르겠습니다.
