### ISSUE TITLE
[2주차] 0.1 + 0.2 == 0.3이 false인 이유가 뭔가요?

### ISSUE THREAD

**Issue by wonju-dev** [KMUCS-MoGakKo/Java_Study#7]
리터럴을 공부하다가

``` java
System.out.println(0.1 + 0.2 == 0.3); // false
```
의 결과가 `false`가 나오는 것을 확인했습니다. 이유가 무엇일까요?

컴퓨터가 부동소수점을 어떻게 저장하는지 알려주시면 좋겠습니다!

**Comment by devbelly** [comment]
자바에서는 실수를 부동소수점 방식으로 표기(부호,지수,가수부로 이루어짐)
0.1와 같은 소수점 아래 부분을 이진수로 변환하기 위해서는 2를 계속 곱해나가면 알 수 있음
0.1 x 2 = 0.2  (0)
0.2 x 2 = 0.4  (0)
0.4 x 2 = 0.8  (0)
0.8 x 2 = 1.6  (1)
0.6 x 2 = 1.2  (1)
0.2 x 2 = 0.4  (0)
0.4 x 2 = 0.8  (0)
0.8 x 2 = 1.6  (1)
0.6 x 2 = 1.2  (1)
....
즉 무한히 반복됨을 확인할 수 있음, 0.2도 마찬가지
표현범위 밖을 벗어난 부분에 대해서는 버리게 되므로 오차 발생

- https://www.secmem.org/blog/2020/06/11/float-2/
- https://velog.io/@maketheworldwise/float-double-%EB%B6%80%EB%8F%99%EC%86%8C%EC%88%98%EC%A0%90
