### ISSUE TITLE
[2주차] 실수를 0으로 나눴을 때 에러가 발생하지 않을 이유가 있을까요?

### ISSUE THREAD

**Issue by identity230c** [KMUCS-MoGakKo/Java_Study#8]
python은 실수를 0으로 나눠도 에러가 발생하던데 

java는 왜 NaN, 음의 무한, 양의 무한이라는 개념으로 처리하는 건가요?

NaN, 무한도 사실 일반적으로 볼 일 없는 개념인데 에러로 넘기지 않는 이유가 궁금합니다

**Comment by wonju-dev** [comment]
오... 정수형을 0으로 나누면 예외가 발생하는데, 실수형은 안 그러네요 
``` java
package operator;

public class Division {
    public static void main(String[] args) {
        try {
            System.out.println(10 / 0);
        } catch (ArithmeticException e) {
            System.out.println(e);
        }

        System.out.println(10/ 0.0); // not error 
        System.out.println(10.0 / 0); // not error
    }
}
```
제가 올린 질문 issue와 연관이 있어보입니다!!

**Comment by devbelly** [comment]
여러 자료를 찾아봤는데 이 설명 외에는 의미있는 설명을 찾기가 어려웠습니다. 간단히 말해서 "IEEE 754"가 그렇게 정의해서 라고 합니다.
- https://stackoverflow.com/questions/12954193/why-does-division-by-zero-with-floating-point-or-double-precision-numbers-not
