### ISSUE TITLE
[2주차] 리터럴로 문자열을 생성하면 장점이 있을까요?

### ISSUE THREAD

**Issue by mjjunng** [KMUCS-MoGakKo/Java_Study#9]
리터럴로 생성한 문자열과 new 연산자로 생성한 문자열의 저장 위치가 다르다는 것을 알게 되었습니다. 리터럴로 문자열을 생성해서 string constant pool에 저장하면, new 연산자로 생성해서 heap에 저장된 문자열과 비교했을 때 장점이 있을까요?

**Comment by wonju-dev** [comment]
https://starkying.tistory.com/entry/what-is-java-string-pool

장점은 아니지만 둘의 차이점을 잘 정리한 글 올려봅니닷

**Comment by devbelly** [comment]
자바에서 string constant pool이 없고 new로만 string을 생성한다면 반복문 내에서 문자열을 선언하는 경우 매번 Heap 영역에서 문자열을 생성하게 될 것입니다. 이는 메모리 낭비 문제 및 성능 문제로 직결될 가능성이 있습니다. 이를 방지하기 위해 리터럴을 통해 문자열을 생성하고 constant pool에 저장하는 방식이 생겼을 것이라고 생각됩니다. 

이 경우 반복문 내에서 리터럴로 string 변수를 선언하게 되면 새로운 객체를 생성하기 전 constant pool을 확인하여 re-usability가 가능합니다.
